### POST request to create a job
POST http://localhost:8080/api/v1/jobs
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "Trabajo 1 para client@gmail.com",
  "description": "Descripcion del trabajo 1",
  "categoryId": "019fb463-f2a7-7426-91aa-4a907a41fc44",
  "budgetAmount": 1100.00,
  "budgetCurrency": "USD",
  "street": "Av. Siempre Viva 123",
  "city": "Montevideo",
  "latitude": -34.901112,
  "longitude": -56.164532
}


### GET request to retrieve all published jobs
GET http://localhost:8080/api/v1/jobs
Content-Type: application/json
Authorization: Bearer {{token}}